version: '3.4'

services:
  redis:
    image: redis
    ports:
      - 6379:6379
  redis_commander:
    image: rediscommander/redis-commander
    ports: 
      - 6378:6378
    depends_on:
      - redis
    environment:
      PORT: 6378
      REDIS_PORT: 6379
      REDIS_HOST: "redis"